name: koha
services:
    koha-db:
        image: mariadb
        restart: always
        environment:
            - PUID=1000
            - PGID=1000
            - MYSQL_ROOT_PASSWORD=koha
            - MYSQL_DATABASE=koha_library
            - MYSQL_USER=koha_library
            - MYSQL_PASSWORD=koha
        volumes:
            - ./mariadb:/var/lib/mysql

    koha-docker:
        restart: always
        environment:
            - PUID=1000
            - PGID=1000
            - NO_MEMCACHED=false
            - DB_HOST=koha-db
            - DB_PORT=3306
#            - MYSQL_DATABASE=koha_library
            - MYSQL_USER=koha_library
            - MYSQL_PASSWORD=koha
            - DB_ROOT_PASSWORD=koha
            - SLEEP=10
            - TIMEZONE=America/New_York
#            - INSTALL_LANG=tr-TR
        ports:
            - 3026:8081
            - 3025:8080
        container_name: koha
        cap_add:
            - SYS_NICE
            - DAC_READ_SEARCH
        build: .
volumes:
  koha-db: